### ISSUE TITLE
0.2.4的父子名称是不是有点错位。

### ISSUE THREAD

**Issue by HopeLHP** [OpaqueGlass/syplugin-hierarchyNavigate#10]
好像文档名称明显比父子两个字高？
<img width="629" alt="image" src="https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/70339118/c9fce574-b99c-4094-b0b5-a6a27e702a97">

---
另外，我发现隐藏导航区父子提示词后，其实也挺好看，但是当没有文档的时候显示“无”，和文档名称这些带文本框有些不一致，是否可以在“无”外面也加一个文本框，这样就可以ui一致，但是以不同颜色区分这个“无”不是文档名称而是提示词，。例如
<img width="914" alt="image" src="https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/70339118/d1141b10-9299-41a5-a5cd-505afcd46e4d">

**Comment by OpaqueGlass** [comment]
感谢反馈❤。

> 好像文档名称明显比父子两个字高？

问题已定位，明天跟着字符数统计一起发新版。

> 是否可以在“无”外面也加一个文本框，这样就可以ui一致，但是以不同颜色区分这个“无”不是文档名称而是提示词，

就我这界面设计能力，emm。
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/b13564b5-39c3-464b-ab9e-30807dd9536e)
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/6cc40c70-cf52-4bf4-9359-599684fbe6fa)

**Comment by HopeLHP** [comment]
> 就我这界面设计能力，emm。

哈哈哈感谢更新！！！

**Comment by OpaqueGlass** [comment]
已经推送到集市了，可以再更新确认一下，谢谢反馈。
