### ISSUE TITLE
非常实用的插件，但更新之后好像显示有点问题？

### ISSUE THREAD

**Issue by Glorenia** [OpaqueGlass/syplugin-hierarchyNavigate#11]
首先感谢作者制作了如此实用的插件！

问题反馈如下：
如图，更新到2.10.1 并更新插件后，出现了>>>这样的图案，不太美观。或许是我哪里没设置好？
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/27939257/d0dd874f-9556-441a-b903-4b6fba251de6)

**Comment by OpaqueGlass** [comment]
我这边还好，如果所有文档都这样，可能是和主题、其他插件或代码片段冲突。可以的话麻烦说一下正在使用的主题、插件，我试着兼容一下。

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/f9730292-0364-48f6-9bbb-9a4876b760aa)
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/ca22cc83-c322-47b4-968a-5b9eaad1b324)

**Comment by Glorenia** [comment]
使用的主题：tsundoko。
使用的插件：
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/27939257/71ee91a1-e507-4c63-858f-a181894ed231)

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/27939257/4fd3bdc7-4dff-4f9f-bfee-a99abb73fa4e)

感谢大大！

**Comment by Glorenia** [comment]
> 使用的主题：tsundoko。 使用的插件： ![image](https://user-images.githubusercontent.com/27939257/263727411-71ee91a1-e507-4c63-858f-a181894ed231.png)
> 
> ![image](https://user-images.githubusercontent.com/27939257/263727479-4fd3bdc7-4dff-4f9f-bfee-a99abb73fa4e.png)
> 
> 感谢大大！

猜测应该是主题的问题，因为切换到原生主题、savor、dark+、onenote，都是可以正常显示的~

**Comment by OpaqueGlass** [comment]
最近没时间尝试，大概两三天后哈。

**Comment by OpaqueGlass** [comment]
已经尝试修复，可以到[https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases)下载测试版。

**Comment by Glorenia** [comment]
> 已经尝试修复，可以到https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases下载测试版。

能正常显示啦~谢谢大大！
