### ISSUE TITLE
关于同级的文档有个需求，能否显示前后的同级文档

### ISSUE THREAD

**Issue by mozhux** [OpaqueGlass/syplugin-hierarchyNavigate#12]
这个主要是应用在日记的时候，能显示前一篇文档、后一篇，不知道能不能做到？这样在日记就能方便前一天的了，后面没有则为空。

**Comment by OpaqueGlass** [comment]
这个样子？
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/c93175e5-108d-4026-b8ce-866f1d2d1a13)

这样的话，有一行文档信息、一行父文档（有些用户选择显示面包屑了）、一行上一篇下一篇、n行子文档。还是全局生效，会不会有点多？😵

目前是，只在文档上层为笔记本的时候才会显示同级的文档。

**Comment by mozhux** [comment]
差不多意思，这个可以是单独的选项，我感觉比同级文档更好点哈哈。

**Comment by OpaqueGlass** [comment]
ok，还是上面的效果，发成beta版了[https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases)，集市上暂时不更新；

**Comment by mozhux** [comment]
> ok，还是上面的效果，发成beta版了https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases，集市上暂时不更新；

收到，已下载体验，就是默认能否再简化一点，我看有.sy的后缀，另外就是那个>>>有点过多？一个感觉好点？其他的都非常不错，很稳定
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/46953371/e83e778e-d107-47b5-ac66-aec6081bcfe5)

**Comment by OpaqueGlass** [comment]
收到，`.sy`后缀算是bug😂
