### ISSUE TITLE
设置项：始终显示同级文档 & 同级文档部分当前文档样式改进

### ISSUE THREAD

**Issue by Aiviokoo** [OpaqueGlass/syplugin-hierarchyNavigate#17]
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/87182333/440fa214-b362-4ecd-bb58-9fd037a609fb)
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/87182333/0d0f4783-119f-40f4-b4e9-491f5a28cccf)

**Comment by OpaqueGlass** [comment]
目前是设计如此：最初设计是只显示父、子两部分，在笔记本首个层级中，没有父文档，所以引入了“兄”这个部分；
后来也有用户反馈显示兄弟文档（同级文档）的话东西太多了，就给了个选项可关闭；

![Here is a image 这里有图片](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/0350fcad-f414-4cee-8d19-69a47058645e)

暂时可以通过点击第二行中的`>`箭头替代，如果仍然有需求，请再回复，之后我加一下；

![Here is a image 这里有图片](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/75865e43-7173-40da-b84c-87f98e6bc93e)

**Comment by Aiviokoo** [comment]
好嘞好嘞，感谢大佬回复，如果不太麻烦的话加个默认关闭的设置吧，麻烦的话就算啦，谢谢

**Comment by OpaqueGlass** [comment]
已经推送到集市；需要在设置项中启用`始终显示同级文档（兄：）部分`
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/0a89ce46-6cca-4f19-999d-03da5ccdb43a)
