### ISSUE TITLE
有时无法显示

### ISSUE THREAD

**Issue by OpaqueGlass** [OpaqueGlass/syplugin-hierarchyNavigate#18]
有时候，点开一个已有的文档，不会显示层级导航，需要切换页签再切换回来之后重新刷新才显示。（概率大概不到10%，可能接近10% 的样子）

_Originally posted by @Aiviokoo in https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/issues/3#issuecomment-1773803272_

**Comment by OpaqueGlass** [comment]
e318caa05253eeb1aa63f9675075c30e5efe3d4c

**Comment by Aiviokoo** [comment]
感谢大佬，安装上新版本后，我先重建了下索引，结束后大概点了100个左右的文档，试了试，均加载成功。很完美。

> [e318caa](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/commit/e318caa05253eeb1aa63f9675075c30e5efe3d4c)
