### ISSUE TITLE
功能优化

### ISSUE THREAD

**Issue by woniuxia** [OpaqueGlass/syplugin-hierarchyNavigate#21]
1. 打开设置界面，没用过的人，可能会不知道下面还有更多的设置项，可以把滚动条设置的稍微宽一些，或者把下面一个设置项，展示一半，表明下面还有更多的设置项
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/16383685/b223bb7c-48ce-4f82-8318-aad321daadf7)

2. 这个功能还挺喜欢的，当前是单独使用 listChildDocs ，期待后续迭代为稳定功能
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/16383685/34b793fc-48d6-47b3-863b-090da3463770)
3. 有一点强迫症，除了兄和子，当前路径和上一篇下一篇前面能否也加个合适的描述，比如当、兄，当前的兄改为同。
4. 还有当前如果兄弟路径过长，第二行的前面可以空出点位置和第一行对齐吗，感觉更美观些。
5. 可不可以自定义这四个信息的顺序，感觉当前路径、兄弟、同级、子，可能更好些，不过也感觉比较个性化。
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/16383685/85c43035-9335-4dd2-bd95-d1837415a74d)

感谢提供好用的插件。

**Comment by OpaqueGlass** [comment]
感谢反馈。
1. 这个使用的是思源的样式，下个版本会把设置页改得长一些，滚动条部分先不修改了，防止和思源整体割裂；
2. 😂最开始比较离谱的功能都标了这个，有的已经没啥bug了；
有其他建议可以再提；
现在不好用的点主要是必须文档为空才显示这个；
另外，插件也引入了快捷键插入listChildDocs，可以在思源设置-快捷键中配置；

3. “当”这个会不会有点尬 ；
  - [ ] 加入`同`；
4. 这个不太确定是否能改，我研究一下；
  - [ ] TODO
5. 暂时改不了，需要首先改造一下插件的设置页面，或许加个拖拽排序，现在项目太简陋了，除了重写，没思路ing；

**Comment by OpaqueGlass** [comment]
自定义顺序不太确定是否会做，现在一个文件里塞了2000多行代码😅，下一步要加功能的话需要重新整理一下。
其他点将在v0.2.9中改进。❤

**Comment by OpaqueGlass** [comment]
hi，最近整出了新版，新版已经支持排序，目前正在测试， 如果可以，请[帮助测试新版](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases/tag/v1.0.0-alpha)，谢谢；

> 另外，关于listChildDocs部分，emm，之前是写成了我这里测试用的路径了，和集市上下载的不同，下个版本应该凑合能用了；挂件另外加载一次，会有点卡；

**Comment by woniuxia** [comment]
大佬，辛苦。
测试PC端自定义排序功能正常，感谢~
