### ISSUE TITLE
通过属性设置支持隐藏父子文档区域

### ISSUE THREAD

**Issue by UltramarineSky** [OpaqueGlass/syplugin-hierarchyNavigate#23]
在父文档上用属性视图做观影列表，想要不显示子文档区域，没找到设置的地方，希望可以通过自定义属性设置来选择是否显示子文档区域

**Comment by OpaqueGlass** [comment]
麻烦明确一下需求：

A. 所有文档都不显示子文档区域；
> 目前只能通过代码片段css设定

B. 只在指定文档不显示子文档区域；
> 目前不支持

C. 只在指定文档不显示所有区域；
> 在文档上设置属性值为 og文档导航忽略

D. 其他；

**Comment by UltramarineSky** [comment]
> 麻烦明确一下需求：
> 
> A. 所有文档都不显示子文档区域；
> 
> > 目前只能通过代码片段css设定
> 
> B. 只在指定文档不显示子文档区域；
> 
> > 目前不支持
> 
> C. 只在指定文档不显示所有区域；
> 
> > 在文档上设置属性值为 og文档导航忽略
> 
> D. 其他；

想要的是B，只在指定文档不显示子文档区域

**Comment by OpaqueGlass** [comment]
ok，感谢反馈，下下周或以后才会开始做，长期来看，可能会扩展到所有区域都可以另外选择是否显示和控制显示顺序，要改的有点多；

> 我先试着加个选项在发现“文档中包含数据库”时不显示子文档吧；做不出来，或者（这个判断范围有点不可控、）你认为没意义的话另说😅

**Comment by OpaqueGlass** [comment]
hi, “文档中包含数据库时不显示子文档”的功能，已经在[v0.2.9(2023-11-14)](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/blob/refactor/CHANGELOG.md#v029-2023%E5%B9%B411%E6%9C%8814%E6%97%A5)版本提供；

在文档属性中自定义显示顺序和是否显示，将在下个版本提供，届时请阅读README；issue将被关闭，感谢反馈。
