### ISSUE TITLE
支持黑名单机制

### ISSUE THREAD

**Issue by woniuxia** [OpaqueGlass/syplugin-hierarchyNavigate#24]
部分文档不想展示该导航。希望可以有个黑名单机制，在黑名单中的文档，不显示文档层级导航。
感谢~

**Comment by OpaqueGlass** [comment]
请参考  https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/issues/23#issuecomment-1807093764  或等待 #23 ；暂无计划在设置界面使用列表配置黑名单，谢谢；

**Comment by OpaqueGlass** [comment]
我补充一下吧😂，目前是有个类似的功能，所以不打算做黑名单列表；

> 带有`og-hn-ignore`或`og文档导航忽略`属性或属性值的文档将被忽略，不显示层级导航；

**Comment by woniuxia** [comment]
已经使用该方法解决了。感谢~
