### ISSUE TITLE
插件会影响思源导出pdf只能导出一页

### ISSUE THREAD

**Issue by mozhux** [OpaqueGlass/syplugin-hierarchyNavigate#25]
通过控制变量测试发现最新版思源2.10.16和最新版插件可能有冲突的地方，导出pdf只会随机某部分且只有一页，暂停插件后正常。
我的插件设置如下：
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/46953371/f4f0b660-461d-4166-9ee4-032cfc080ef2)
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/46953371/d665ba56-6cd4-4fbb-b8ad-1000cf51a5be)
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/46953371/b8d53de6-21f6-420f-ae7e-007f9150ee88)
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/46953371/e30130dc-484f-49cc-8104-b81d59da3e3b)

**Comment by OpaqueGlass** [comment]
> https://ld246.com/article/1700546515477 
大概是排除插件的问题
