### ISSUE TITLE
能不能基于文档的索引关系来显示导航？

### ISSUE THREAD

**Issue by leommjj** [OpaqueGlass/syplugin-hierarchyNavigate#26]

**Comment by OpaqueGlass** [comment]
烦请解释一下什么是文档的索引关系❔目前是按照文档树排序取的；

**Comment by leommjj** [comment]
文档的引用关系就是：被双括号应用的意思，排除块引用。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpaqueGlass/syplugin-hierarchyNavigate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月22日(星期三) 中午1:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpaqueGlass/syplugin-hierarchyNavigate] 能不能基于文档的索引关系来显示导航？ (Issue #26)





 
烦请解释一下什么是文档的索引关系❔目前是按照文档树排序取的；

**Comment by leommjj** [comment]
可能作者你是用文档树来组织笔记的（page），这样来看这个插件没什么问题。我的考虑是一部分人的使用逻辑是类roam的逻辑，就是不用文档树，用page来管理page。这个大家都知道，因此我指的是这种用法的情况下，作者你的插件就起不到作用了，比如我就是全部文档放在一个笔记本里面，是没有文档树层级关系的。  当然思源本身在文档的题头处有显示当前文档的被引用个数，鼠标点击也能显示，我的想法是能不能直观的显示处理，就是类似现在你这个插件的效果。

**Comment by OpaqueGlass** [comment]
或许我理解了；但还有一些问题：

0. 这个需求反向链接面板可以满足吗？
    ![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/4587fa9c-2466-4612-8bac-8c981a7ed93a)

> 如果能够满足，我就不做了；
> 避免做一些自己用不到的东西，开发自己都不常用的功能，大多体验不好；

1. 具体显示什么？

> 如果说反向链接面板不能满足的需求，我想可能有不能排除块引用，以及没有正向链接，这两点；
>
> 是需要显示 文档正向链接 与 反向链接 到的文档吗？
> 还是面包屑？目前面包屑是根据文档树给出的，引用关系多对多，不能给出这样的显示。

2. 排序如何决定？

> 不像文档树，文档树中的文档有固定的排序方式，用户也可以在文档树拖拽自定义；
> 要获取正向链接只能通过sql，排序方式较为有限；
> 按照我目前的了解，能做的排序大概只有根据文档名称字母排序或文档修改时间排序（名称自然排序还需要插件自己实现😅），不能按照引用在文中的位置排序；

3. 图标？

> 文档树API一并提供了文档图标；我没仔细看，按照目前我的了解，引用API不提供文档图标的返回；这样的话，要显示只能一个文档发一个请求获取，响应存在延迟；

4. 显示位置？

> 如果要做的话，大概会作为类似当前“子文档”区域一样的平级区域？；

另外，就算要做，一时半会儿无法开始，我需要先抽时间重构垃圾代码（一个文件塞了2千多行的代码，之前有大佬想PR都无从下手😅）；重构之后，上述问题都有明确答案的话可以考虑；

**Comment by OpaqueGlass** [comment]
具体实现不用管，就是上面的问题，你的需求是什么？以及你觉得常用吗？

**Comment by leommjj** [comment]
0 能用，但是操作体验不好，这里显示的是所有引用关系（块和文档型都有），另外，直接展示和点击直达这两个优点，是反链没有的（这一步包含了查询、过滤掉块引用等等，有没有结果？没有就是负反馈）。另外为什么要过滤块引用？因为文档级别的page通常是一个概念，比如数学这个page引用小学数学；这也是为什么类roam软件的反链只显示page级别的反链，只是概念和线索的区别，我喜欢把块引用叫成线索。1 只显示page级别的文档名称，这是肯定的，参照logseq等软件，貌似只显示父级文档，就是这个概念从哪里来？可以快速回溯，至于子级，你看吧。
2 排序应该都是还修改时间吧，这个我不清楚
3 是指文档图标吗？我觉得有标题就行
4 显示位置就在题头图？像现在这样。logseq就是平铺的。








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月22日(星期三) 下午2:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OpaqueGlass/syplugin-hierarchyNavigate] 能不能基于文档的索引关系来显示导航？ (Issue #26)





 
或许我理解了；但还有一些问题：
  
这个需求反向链接面板可以满足吗？
 
   
如果能够满足，我就不做了；
 避免做一些自己用不到的东西，开发自己都不常用的功能，大多体验不好；
   
具体显示什么？
   
如果说反向链接面板不能满足的需求，我想可能有不能排除块引用，以及没有正向链接，这两点；
 
是需要显示 文档正向链接 与 反向链接 到的文档吗？
 还是面包屑？目前面包屑是根据文档树给出的，引用关系多对多，不能给出这样的显示。
   
排序如何决定？
   
不像文档树，文档树中的文档有固定的排序方式，用户也可以在文档树拖拽自定义；
 要获取正向链接只能通过sql，排序方式较为有限；
 按照我目前的了解，能做的排序大概只有根据文档名称字母排序或文档修改时间排序（名称自然排序还需要插件自己实现😅），不能按照引用在文中的位置排序；
   
图标？
   
文档树API一并提供了文档图标；我没仔细看，按照目前我的了解，引用API不提供文档图标的返回；这样的话，要显示只能一个文档发一个请求获取，响应存在延迟；
   
显示位置？
   
如果要做的话，大概会作为类似当前“子文档”区域一样的平级区域？；
  
另外，就算要做，一时半会儿无法开始，我需要先抽时间重构垃圾代码（一个文件塞了2千多行的代码，之前有大佬想PR都无从下手😅）；重构之后，上述问题都有明确答案的话可以考虑；

**Comment by leommjj** [comment]
我觉得这个就是类roam使用逻辑，在思源上的补充；而这个显示逻辑在任何一款类roam软件上都是一样的（还支持搜索，思源其实有点和ob有点像，是全文反链）；这个想法重不重要或者说使用频率是肯定的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月22日(星期三) 下午2:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OpaqueGlass/syplugin-hierarchyNavigate] 能不能基于文档的索引关系来显示导航？ (Issue #26)





 
具体实现不用管，就是上面的问题，你的需求是什么？以及你觉得常用吗？

**Comment by leommjj** [comment]
> 我觉得这个就是类roam使用逻辑，在思源上的补充；而这个显示逻辑在任何一款类roam软件上都是一样的（还支持搜索，思源其实有点和ob有点像，是全文反链）；这个想法重不重要或者说使用频率是肯定的。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月22日(星期三) 下午2:19 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [OpaqueGlass/syplugin-hierarchyNavigate] 能不能基于文档的索引关系来显示导航？ (Issue #26) 具体实现不用管，就是上面的问题，你的需求是什么？以及你觉得常用吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

只不过roam的反链筛选是基于page的，且附带了布尔筛选的逻辑？什么是布尔筛选，你应该知道吧。

**Comment by OpaqueGlass** [comment]
@_@

我没用过这种笔记形式，我去下个logseq试一下
再确认一下：

> 只显示page级别的文档名称，这是肯定的，参照logseq等软件，貌似只显示父级文档，就是这个概念从哪里来？

思源数据库能够给出的是：

当前文档链接到了哪些文档；（正向链接）
哪些文档中有当前文档的链接；（反向链接）

这更多是个引用和被引用的关系，我不清楚上面能否反映”这个概念从哪里来”、“父级”的问题

**Comment by leommjj** [comment]
> k
> Quote r

就是（反向链接），roam类软件，只显示反向链接

**Comment by OpaqueGlass** [comment]
哦哦；

> 只不过roam的反链筛选是基于page的，且附带了布尔筛选的逻辑？什么是布尔筛选，你应该知道吧。

刚去查了一下，布尔筛选我大概做不了哈；思源自己的搜索我都觉得难用

**Comment by leommjj** [comment]
> 哦哦；
> 
> > 只不过roam的反链筛选是基于page的，且附带了布尔筛选的逻辑？什么是布尔筛选，你应该知道吧。
> 
> 刚去查了一下，布尔筛选我大概做不了哈；思源自己的搜索我都觉得难用

我知道这个应不好做，只是安利一下

**Comment by leommjj** [comment]
尝试过roam你会体验到他们反链面板的好处

**Comment by OpaqueGlass** [comment]
ok，我试试😀

**Comment by OpaqueGlass** [comment]
如果可以，麻烦测试一下 https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases/tag/v0.2.10-beta1 这个版本。我不确定是否是你想要的效果。

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/3974e0cd-81b8-449e-a34b-8d13c0eab6aa)

**Comment by leommjj** [comment]
强






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月28日(星期二) 中午1:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OpaqueGlass/syplugin-hierarchyNavigate] 能不能基于文档的索引关系来显示导航？ (Issue #26)





 
如果可以，麻烦测试一下 https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases/tag/v0.2.10-beta1 这个版本。我不确定是否是你想要的效果。
 
image.png (view on web)

**Comment by leommjj** [comment]
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/101880110/34bcfd5a-dd31-4afd-bcb8-fdfc72a44f7d)
解包后，插件无法开启；开启后再返回插件界面，还是关闭的

**Comment by OpaqueGlass** [comment]
文件夹需要重命名，`package`改为`syplugin-hierarchyNavigate`

**Comment by leommjj** [comment]
OK了。发现了

**Comment by leommjj** [comment]
强！是这个意思。
另外，有一点分享：就是思源论坛老生常谈的问题——文档树的去留？我举了个例子：可以看到反链的集合大于文档树的集合；
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/101880110/4059a3ff-574d-4d1c-9cc6-70fd518d7227)
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/101880110/7ea78575-c8ed-4bba-8e60-0a115f56961b)
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/101880110/34cdb696-794d-4f19-94f5-ad00451e1f2b)
另外，roam类软件的反链面板只能看出来文档的父级，子级是没有的；为此采用了别的方式，以logseq为例子：


是通过[[父级文档名称/子级文档名称]]，以这个形式来组织的。可以看到这种方式更加贴合双链的用法。

**Comment by leommjj** [comment]
![6fbc10fb14cb61333370b14d3b64744](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/101880110/01f72d39-b8ed-4453-9622-bc5c4df3d9bf)

**Comment by leommjj** [comment]
结论就是无所谓什么文档树，主要是思源没有给出完整的双链使用方案。

**Comment by OpaqueGlass** [comment]
> 我现在还是在用文档树😂
> 我大致理解的 这里的子级的概念是 如果是块b引用了文档A，父级是b所在的文档B、子级是块b。
> 我最近不常记笔记，是该找个时间整理一下笔记了😅

现在层级导航的设计只是个链接，同一个区域视为平级的，加上子级关系不在最初的设计范围内；或许可以期待一下其他大佬开发的反链面板插件；

**Comment by leommjj** [comment]
只要把需要建立层级的文档，用文档树就行了，就能从logseq过渡到思源；唯一的区别是需要先在文档树找到这个文档。

**Comment by OpaqueGlass** [comment]
ok❤我试一下；
这个issue就先这样了哈。

**Comment by leommjj** [comment]
好，感谢。emo：如果能把logseq的逻辑给思源设计一套就好了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月28日(星期二) 下午3:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OpaqueGlass/syplugin-hierarchyNavigate] 能不能基于文档的索引关系来显示导航？ (Issue #26)





 
ok❤我试一下；
 这个issue就先这样了哈。

**Comment by OpaqueGlass** [comment]
我这儿一时半会不会做这个，其他破事有点多😂

这个大佬好像在写和反链面板相关的内容，方向重合的话可以提议一下（？）

https://ld246.com/article/1701016463363

https://github.com/Wetoria/sy-plugin-wetoria
