### ISSUE TITLE
能够在闪卡复习页面显示

### ISSUE THREAD

**Issue by QQQOrange** [OpaqueGlass/syplugin-hierarchyNavigate#33]
闪卡复习页面的面包屑显示的非常不直观并且内容显示的不完整，要是此插件能在闪卡复习页面显示那就再好不过了，非常感谢

**Comment by OpaqueGlass** [comment]
目前没时间，先保持开启，处理完其他issue后再确认，谢谢。

**Comment by QQQOrange** [comment]
> 目前没时间，先保持开启，处理完其他issue后再确认，谢谢。

谢谢大佬

**Comment by OpaqueGlass** [comment]
目前插件的代码沉重了（只有一个代码文件、并且里面塞了2300行），本来计划是这个月换个框架重写一下（但，我还不会在框架下写个我想要的设置界面，估计这个月搞不定了）；在这个垃圾代码上继续堆会比较快，但越堆越不稳定，所以加新功能的事情在搁置中……

只是显示面包屑的话，在我另一个插件可能可以加一下（一样是单文件的垃圾代码，但那边没计划重构），大概效果就是下面这样

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/3aa9aa24-f39d-46ec-9090-6771dbdb9f89)

但同时，也会在文档（所有的文档编辑器）插入这个；

> （见到面包屑就加，太抽象了，感觉可能和其他插件冲突；都塞一行还会挤😅）

**Comment by QQQOrange** [comment]
> 目前插件的代码沉重了（只有一个代码文件、并且里面塞了2300行），本来计划是这个月换个框架重写一下（但，我还不会在框架下写个我想要的设置界面，估计这个月搞不定了）；在这个垃圾代码上继续堆会比较快，但越堆越不稳定，所以加新功能的事情在搁置中……
> 
> 只是显示面包屑的话，在我另一个插件可能可以加一下（一样是单文件的垃圾代码，但那边没计划重构），大概效果就是下面这样
> 
> ![image](https://private-user-images.githubusercontent.com/52985952/296253369-3aa9aa24-f39d-46ec-9090-6771dbdb9f89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMDY0ODcsIm5iZiI6MTcwNTEwNjE4NywicGF0aCI6Ii81Mjk4NTk1Mi8yOTYyNTMzNjktM2FhOWFhMjQtZjM5ZC00NmVjLTkwOTAtNjc3MWRiZGI5Zjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDAwMzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYzNjMTgxODk4NGIyMzIzZDFkMmEyYTRjZGUyODg0N2E3M2IzYWNkZTEyZDdkMTQ4OWZkOWUyZDk1MmMxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eEiGYZOIhkrBJDZ2XTqd6rw2ebUXmKZYEmGuECh-yFk)
> 
> 但同时，也会在文档（所有的文档编辑器）插入这个；
> 
> > （见到面包屑就加，太抽象了，感觉可能和其他插件冲突；都塞一行还会挤😅）
> 
> 在这边加这个功能的话，前置任务是： #28

okk 有盼头比啥都强！！！！非常感谢大佬！！！！！！

**Comment by OpaqueGlass** [comment]
在文档面包屑插件v0.2.11中，已经引入了上面说的功能，需要开启插件设置项`在更多情况下显示文档面包屑`

**Comment by QQQOrange** [comment]
> 在文档面包屑插件v0.2.11中，已经引入了上面说的功能，需要开启插件设置项`在更多情况下显示文档面包屑`

用上了，用上了，老哥牛逼！！！！！

请教一下，如果面包屑太多的话，它会自动换行吗

**Comment by OpaqueGlass** [comment]
这部分没有做处理，目前的设置是超过5个会折叠，像下面这样
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/22672a5e-d2a2-42ab-87f1-a8dd77a44ba2)

**Comment by QQQOrange** [comment]
> 这部分没有做处理，目前的设置是超过5个会折叠，像下面这样
> ![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/22672a5e-d2a2-42ab-87f1-a8dd77a44ba2)
> 

嗷嗷嗷嗷 老哥牛逼！！！

通过老哥的这个插件，可以简单的实现remnote的相关样式。 虽然不是100%还原，但能用就行。笔芯！！！！

**Comment by QQQOrange** [comment]
> 这部分没有做处理，目前的设置是超过5个会折叠，像下面这样 ![image](https://private-user-images.githubusercontent.com/52985952/297955608-22672a5e-d2a2-42ab-87f1-a8dd77a44ba2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDUxOTMsIm5iZiI6MTcwNTY0NDg5MywicGF0aCI6Ii81Mjk4NTk1Mi8yOTc5NTU2MDgtMjI2NzJhNWUtZDJhMi00MmFiLTg3ZjEtYThkZDc3YTQ0YmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMDE5ZGFjMjE2ZDA0YjliZmRkODkwMGI2YTdhODM0M2U2MDlhNzY1NTVjYTMzZWFiZDY5ZTQ2MTBmZTFiMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AakJN-Id5tKEKd0Kj6pGJ7WT2H65V0Fv-yhDZDqvdKU)

等老哥另一个插件的相关功能出来，对remnote不就直接爆杀

**Comment by OpaqueGlass** [comment]
什么功能呢？

**Comment by QQQOrange** [comment]
> 什么功能呢？

文档层级导航插件在闪卡复习页面中显示的功能呀，之前老哥不是说后续会考虑吗

**Comment by QQQOrange** [comment]
> 我感觉差不多，主要是需要用哪个部分呢？反链吗？
> 会做，但估计只是照搬到闪卡界面，没感觉会有什么用（？）

照搬就可以了呀，主要就是知道目前刷了这张卡是来源于哪里

**Comment by QQQOrange** [comment]
> 我感觉差不多，主要是需要用哪个部分呢？反链吗？
> 会做，但估计只是照搬到闪卡界面，没感觉会有什么用（？）

面包馅儿的话显示起来不太直观。

**Comment by OpaqueGlass** [comment]
ok，明白了

**Comment by OpaqueGlass** [comment]
hi, 如果可以，请[帮助测试新版](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases/tag/v1.0.0-alpha)，谢谢；

**Comment by QQQOrange** [comment]
> hi, 如果可以，请[帮助测试新版](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases/tag/v1.0.0-alpha)，谢谢；

好的好的，我现在就试试

**Comment by QQQOrange** [comment]
> hi, 如果可以，请[帮助测试新版](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases/tag/v1.0.0-alpha)，谢谢；

目前正在使用中，并且使用过程中暂未遇见 bug。若遇见，则会在问题页面提出，非常感谢老哥的插件 比心
