### ISSUE TITLE
看子文档快捷键

### ISSUE THREAD

**Issue by QQQOrange** [OpaqueGlass/syplugin-hierarchyNavigate#34]
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/62794181/1cf9a23a-ce0f-4cf7-85c9-50ebda12a1ac)
目前插件快捷键可以看上下以及父文档，希望添加一个看子文档的快捷键，这样阅读导入的书籍时更加的快捷，谢谢大佬

**Comment by OpaqueGlass** [comment]
已在 v0.2.11 (2024年2月1日) 版本更新。

**Comment by QQQOrange** [comment]
> 已在 v0.2.11 (2024年2月1日) 版本更新。

已经用上了，谢谢老哥
