### ISSUE TITLE
如何修改og-hierachy-navigate-doc-container容器的高度

### ISSUE THREAD

**Issue by vm0100** [OpaqueGlass/syplugin-hierarchyNavigate#35]
Hi，请问如何能修改**og-hierachy-navigate-doc-container**容器的高度呢

因为我对“**子文档容器CSS**”设置了以下css将子文档调整为纵向排列了，所以容器的最大高度会导致出现下面截图效果，所以想调整容器的最大高度
```css
display: flex;
flex-direction: column;
align-items: baseline;
```

如果我使用“**链接样式CSS**”设置会将默认样式清空，但是我不想清空默认样式，仅仅只想把max-height设置为auto;
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/28549702/7e47ddb9-8692-4a44-af3a-787dc35862cb)

**Comment by OpaqueGlass** [comment]
有个设置项，既然已经close了，可能你已经找到了？
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/4daf8908-7fc7-43a9-8266-913b70d4e8d1)

或者直接在css那里加`max-height: none`，这个我不确定下个版本（不知道什么时候）的更新可能会让它失效。

这个css挺有意思的❤
