### ISSUE TITLE
文档数量过大，会导致软件持续通知 & 文档最大数量设置较少时引发的bugs

### ISSUE THREAD

**Issue by rumengsiji** [OpaqueGlass/syplugin-hierarchyNavigate#36]
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/63029384/ea8ae540-17ac-444b-b48f-fe105a71f219)
可见此处问题：[点击](https://ld246.com/article/1706681659402)
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/63029384/c1b5561d-2c48-4137-9538-9f53060d25e6)

**Comment by OpaqueGlass** [comment]
收到；
没有显示需求的话，把插件设置、文档最大数量改到`0`；
我在想是给思源加个无聊的PR屏蔽这个通知，还是我这边请求全部子文档列表，再截断；

**Comment by OpaqueGlass** [comment]
fixed in v0.2.11，请在集市更新版本，如果仍有问题，麻烦反馈，谢谢
