### ISSUE TITLE
最新测试版在开启后关闭，已有的导航会显示成这样

### ISSUE THREAD

**Issue by QQQOrange** [OpaqueGlass/syplugin-hierarchyNavigate#38]
关闭后并未重启思源
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/62794181/f488fe32-4609-42f1-b14e-c30b1a6274d5)
重启后恢复正常

**Comment by OpaqueGlass** [comment]
是关闭插件了吗？关闭插件目前确实只移除了样式，没有移除已有的导航区，感谢反馈

**Comment by QQQOrange** [comment]
> 是关闭插件了吗？关闭插件目前确实只移除了样式，没有移除已有的导航区，感谢反馈

期待早日修复哈

**Comment by OpaqueGlass** [comment]
ok。感觉一般不再用了的话才会关插件吧😂

**Comment by QQQOrange** [comment]
> ok。感觉一般不再用了的话才会关插件吧😂

因为在测试嘛，就会多出一些通常不会出现，但低频率会出现的操作。

**Comment by OpaqueGlass** [comment]
ok,修过啦

**Comment by QQQOrange** [comment]
> ok,修过啦

妥妥的
