### ISSUE TITLE
最新测试版 手机端闪卡显示只能显示一部分

### ISSUE THREAD

**Issue by QQQOrange** [OpaqueGlass/syplugin-hierarchyNavigate#39]
最好能一次显示全部。![Screenshot_20240225_121304.jpg](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/62794181/17af81e8-5dc1-497b-95d0-efd3534e6294)

**Comment by OpaqueGlass** [comment]
上下滚动一下应该能看吧，太长了就把闪卡挤没了；另外，下面这个设置应该有用
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/6ad0e449-88fb-4345-9b6a-250be1324a56)

**Comment by QQQOrange** [comment]
> 上下滚动一下应该能看吧，太长了就把闪卡挤没了；另外，下面这个设置应该有用 ![image](https://private-user-images.githubusercontent.com/52985952/307566098-6ad0e449-88fb-4345-9b6a-250be1324a56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MzY0ODUsIm5iZiI6MTcwODgzNjE4NSwicGF0aCI6Ii81Mjk4NTk1Mi8zMDc1NjYwOTgtNmFkMGU0NDktODhmYi00MzQ1LTliNmEtMjUwYmUxMzI0YTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA0NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNzg0NGNkNjE0NTViOWZlOGM5ZTlhY2NmMjM3MTdhZGFmMzQxNDFlYjViZDdmNmUwZjI3MzI3MmU0ZjgzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BeKCf_OWw8ZLsJWfXpnp-9nDG2BO26AJHJsouQ9feDw)

好嘞，谢谢老哥 我去试试康康

**Comment by OpaqueGlass** [comment]
感谢参与测试，我这边将在集市更新正式版，要关闭issue啦。

**Comment by QQQOrange** [comment]
> 感谢参与测试，我这边将在集市更新正式版，要关闭issue啦。

好呀好呀。
