### ISSUE TITLE
自动获取标题

### ISSUE THREAD

**Issue by tongzi001** [OpaqueGlass/syplugin-hierarchyNavigate#40]
网页内容粘贴到文档，能否自动将文档的第一行（或到第二行）作为标题，自动去除特殊符号、空格后，填充目录标题？
经常需要复制网页的内容，整理知识点，每次都要回头去弄标题，还要去除特殊符号，非常不便，

**Comment by OpaqueGlass** [comment]
暂时我认为和两个插件现有功能关系并不大，摸鱼了一个新的；（旧代码结构）

~~看着需求挺简单，思源也有现成的api。有的粘贴格式不能处理，还有问题的话，可以反馈，但我不一定能修；~~ 好像理解错你的意思了，不过凑合用，暂时不改了 https://github.com/OpaqueGlass/syplugin-my-plugin-collection/tree/new

此外，和这里的提议有何不同呢？ https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/issues/9

最后，我这里没有打算做整合很多内容的工具箱插件，新功能提议尽量和插件相关；在群里发个悬赏，会有大佬做的更快更好的。

> 又看了一下更改历史，既然把标题栏改成了目录标题，这里的目录是什么？

**Comment by OpaqueGlass** [comment]
hi, 此issue将被关闭，如有疑问，请继续跟帖回复🙏。
