### ISSUE TITLE
自动获取标题

### ISSUE THREAD

**Issue by tongzi001** [OpaqueGlass/syplugin-hierarchyNavigate#42]
网页内容粘贴到思源笔记，标题栏内容能否自动获取？
将第一行或到第二行内容作为标题，自动提取到标题栏

**Comment by OpaqueGlass** [comment]
emm，这个我应该在 #40 中回复了吧，功能加在一个新插件了，如果有问题，请在原issue中回复，谢谢。

duplicate of #40

**Comment by OpaqueGlass** [comment]
我将关闭此issue，请参考上面的回复，谢谢。
