### ISSUE TITLE
闪卡增加标题的面包屑

### ISSUE THREAD

**Issue by HibernalGlow** [OpaqueGlass/syplugin-hierarchyNavigate#43]
给思源本体提过[issue](https://github.com/siyuan-note/siyuan/issues/10551#issuecomment-1986689613)
面包屑类remnote界面除移动端均可使用闪卡增强插件完成，对于结构化的知识，面包屑的作用相当重要
移动端的面包屑可以说完全起不到这种作用，最新版本的更新发现闪卡界面的面包屑在移动端也生效，（效果很好，就是加载太慢）。
标题可以折行显示，只要能全部看到就行

**Comment by OpaqueGlass** [comment]
hello, 没有完全理解需求，再确认一下

1. 是类似思源现有的块面包屑吗？
2. 只包含标题？在列表中的闪卡需要显示上个列表节点吗？（例如下图，需要详细到哪个节点？）
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/23240bac-aee1-4c8b-8537-5eda460ef8ad)


其他说明：
1. 摸鱼慢，将作为一个新的内容区存在，只能说进入等待队列哈；
2. 为避免重复，桌面端将不显示；
3. 标题将名称遵循“通用”中的文档名最大显示长度，面包屑整体将不做折叠；内容区高度跟随“外观、CSS”中的最大高度限制；效果应该和现在的文档面包屑内容区一样；
4. 看了一下，移动端加载要1.3秒（大概），同样的内容桌面端0.4秒（大概）；主要应该是差在设备性能/移动端API响应速度上，其次是插件要走一下自己的判断过程，暂时无法优化。

**Comment by HibernalGlow** [comment]
我通常以标题制作闪卡，所以应该是到当前标题/内容的母标题，其他我没意见

**Comment by HibernalGlow** [comment]
移动端API响应速度需要提issue吗

**Comment by OpaqueGlass** [comment]
> 移动端API响应速度需要提issue吗

没啥必要，单个api也就差了30ms的样子，可能我这串行请求多了就明显了？

我试试改成异步的，并发一下

> 我通常以标题制作闪卡，所以应该是到当前标题/内容的母标题，其他我没意见

那相较于块面包屑，我打算只显示标题，不显示段落块的内容，列表的上一个节点我看看能否区分一下；

**Comment by HibernalGlow** [comment]
额，我标题制卡和其他制卡大概五五分，毕竟有时候标题不太合适。考虑到其他人笔记习惯（大纲之类），感觉块面包屑毕比较通用一点。

**Comment by OpaqueGlass** [comment]
反骨😂，不想做个和面包屑一样的东西；

列表的话显示到上一个层级，标题的话也显示到上一个标题，段落的话不显示当前段落；大概就是不显示当前节点吧

**Comment by HibernalGlow** [comment]
不是反骨是特色

**Comment by OpaqueGlass** [comment]
麻烦试一下这个版本：
[package.zip](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/files/14549678/package.zip)


- [ ] 判断桌面端、不在桌面端显示；
- [ ] `>`实际不可以点击，调整`>`的样式，取消点击效果；

**Comment by HibernalGlow** [comment]
![1710065467915.png](https://img2.imgtp.com/2024/03/10/ZFffNa1G.png)
![1710066470527.png](https://img2.imgtp.com/2024/03/10/flOl5oQe.png)
![1710065777358.png](https://img2.imgtp.com/2024/03/10/vHZEOAhG.png)
PC端可以显示移动端不行

**Comment by HibernalGlow** [comment]
建议：如果要保留标题前图标的话可以用2️⃣这种，列表也是
![1710065952682.png](https://img2.imgtp.com/2024/03/10/biphAWjo.png)

**Comment by HibernalGlow** [comment]
另外，在闪卡暂停出来之前我都是有母子文档控制闪卡范围的（番茄工具箱的暂停不适合我），但是手机打开文档闪卡实在有点繁琐，有什么好办法吗

**Comment by OpaqueGlass** [comment]
> PC端可以显示移动端不行

这个我在尝试复现，看样子是有个比较严重的bug会导致插件回滚到默认设置

> 建议：如果要保留标题前图标的话可以用2️⃣这种，列表也是

每个层级都不一样吗？不好做，回来再确认

> 另外，在闪卡暂停出来之前我都是有母子文档控制闪卡范围的（番茄工具箱的暂停不适合我），但是手机打开文档闪卡实在有点繁琐，有什么好办法吗

我不常用闪卡，不太了解，可以上社区问问

**Comment by HibernalGlow** [comment]
嗯，那不显示图标也行，正好做区分

**Comment by HibernalGlow** [comment]
另外，加载的速度好像有点问题，这个列表闪卡加载用了30s，其他正常
![1710068212131.gif](https://img2.imgtp.com/2024/03/10/S0x4XMP9.gif)

**Comment by OpaqueGlass** [comment]
> 另外，加载的速度好像有点问题，这个列表闪卡加载用了30s，其他正常

这个不太能确定问题，每次这个闪卡都这样吗？
如果是的话，麻烦截图一下插件日志：思源设置、外观、代码片段、js加入以下内容（记得启用代码片段），重新操作
```js
(function(){
window.top["OpaqueGlassDebug"] = true;
window.top["OpaqueGlassDebugV2"] ={
     "none": 1
    ,"hn": 5
}
})();
```
然后 `ctrl+shift+I`打开开发者工具、console或者控制台，
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/bfbe0ab5-8fa8-4d65-9bad-c9f15500d73f)
截图最后的或出现红色报错的

**Comment by HibernalGlow** [comment]
> > 另外，加载的速度好像有点问题，这个列表闪卡加载用了30s，其他正常
> 
> 这个不太能确定问题，每次这个闪卡都这样吗？ 如果是的话，麻烦截图一下插件日志：思源设置、外观、代码片段、js加入以下内容（记得启用代码片段），重新操作
> 
> ```js
> (function(){
> window.top["OpaqueGlassDebug"] = true;
> window.top["OpaqueGlassDebugV2"] ={
>      "none": 1
>     ,"hn": 5
> }
> })();
> ```
> 
> 然后 `ctrl+shift+I`打开开发者工具、console或者控制台， ![image](https://private-user-images.githubusercontent.com/52985952/311504545-bfbe0ab5-8fa8-4d65-9bad-c9f15500d73f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNjkxODEsIm5iZiI6MTcxMDA2ODg4MSwicGF0aCI6Ii81Mjk4NTk1Mi8zMTE1MDQ1NDUtYmZiZTBhYjUtOGZhOC00ZDY1LTliYWQtYzlmMTU1MDBkNzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDExMDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZDEzMjA3YWY5M2ZiMDkxNjNhNTQzY2FkYmJjNDRlYWNiMGE1YWVlZDNhZDE0MTY5MjMwNzJhNmZjNWY0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tfR8-kzjb-zl6LjdbIFytMimu7RsAkSbwMKM0BzRJBQ) 截图最后的或出现红色报错的

偶发的，复现概率挺低的

**Comment by OpaqueGlass** [comment]
那就难搞了，不过也可能和移动端刚发现的问题相同；

麻烦再试试这个版本：

[package.zip](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/files/14549992/package.zip)

这个版本没有改emoij，原本打算是，1、如果可以的话，大概是变成块面包屑一样的icon来表示类型；2、定死了某些emoji来区分标题层级和列表项；
你之前说的使用1、2这种emoji是表示标题层级吗？应该可以，等明后天吧，今天不修了。

> 之前的bug可能导致插件设置变回默认设置，这个版本改了一下，我这儿暂时没重现；
> 你那边移动端的插件设置可能变回默认了，打开块面包屑，再用电脑端的覆盖一下吧。

**Comment by HibernalGlow** [comment]
面包屑一样的icon也可以

**Comment by HibernalGlow** [comment]
![1710072686866.png](https://img2.imgtp.com/2024/03/10/dLaT0AXJ.png)
浏览器移动端行了，原生移动端不行诶

**Comment by HibernalGlow** [comment]
文件是被同步过去了的

**Comment by HibernalGlow** [comment]
等一下，我退出重进又可以了

**Comment by OpaqueGlass** [comment]
再观察看看，好像同步之后并不会重载插件_(•̀ω•́ 」∠)_

**Comment by HibernalGlow** [comment]
目前是都能用，就是pc隐藏问题，辛苦啦

**Comment by HibernalGlow** [comment]
不过pc也可以保留吧，毕竟闪卡增强插件也有可能不生效

**Comment by OpaqueGlass** [comment]
> 不过pc也可以保留吧，毕竟闪卡增强插件也有可能不生效

那就不管了，都显示，我也不想做专门的设置项hhh。

图标现在是下面这样；
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/df2768d8-612a-4d7f-9fa0-a8a2a467dae2)

**Comment by HibernalGlow** [comment]
图标挺好的。显示的话我pc端还是习惯闪卡插件那样的，做个pc开关可以不？

**Comment by OpaqueGlass** [comment]
ok

**Comment by HibernalGlow** [comment]
反馈一个bug。移动端+手机伺服本地浏览器都会出现第一个闪卡面包屑不出现或是很久才出现的问题，pc端不会，不知道是否是之前的bug

**Comment by OpaqueGlass** [comment]
不知道，我这还好，没有办法定位问题；能复现并且你愿意的话就按照这个看下日志吧。

> > 另外，加载的速度好像有点问题，这个列表闪卡加载用了30s，其他正常
> 
> 这个不太能确定问题，每次这个闪卡都这样吗？ 如果是的话，麻烦截图一下插件日志：思源设置、外观、代码片段、js加入以下内容（记得启用代码片段），重新操作
> 
> ```js
> (function(){
> window.top["OpaqueGlassDebug"] = true;
> window.top["OpaqueGlassDebugV2"] ={
>      "none": 1
>     ,"hn": 5
> }
> })();
> ```
> 
> 然后 `ctrl+shift+I`打开开发者工具、console或者控制台， ![image](https://private-user-images.githubusercontent.com/52985952/311504545-bfbe0ab5-8fa8-4d65-9bad-c9f15500d73f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjg4NTksIm5iZiI6MTcxMDIyODU1OSwicGF0aCI6Ii81Mjk4NTk1Mi8zMTE1MDQ1NDUtYmZiZTBhYjUtOGZhOC00ZDY1LTliYWQtYzlmMTU1MDBkNzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA3MjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NzUwOGVlMzBhZmYzNjgzYTQxNDRkYTdjOGY0ODliNWI2MjU2ZjU3NmUwZjM2MmI1ZDU3YjhjNmE2YzljYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z9_IvI_Z0x3Ua6fkcd08HjMJrDFHP-x4dASMoMZePzM) 截图最后的或出现红色报错的

**Comment by HibernalGlow** [comment]
那估计就是手机的性能问题

**Comment by OpaqueGlass** [comment]
安卓是屏幕关闭之后就开始卡，但这应该不会区分第一个闪卡才对

**Comment by HibernalGlow** [comment]
我测一下

**Comment by HibernalGlow** [comment]
![1710232708452.png](https://img2.imgtp.com/2024/03/12/htvZRKxP.png)
看一下，第一个尤其慢(5s以上）后面正常

**Comment by HibernalGlow** [comment]
![1710232815568.png](https://img2.imgtp.com/2024/03/12/REdHg462.png)
刷新了以后第一个也是（不过这个不怎么影响使用，不好修就算了吧）

**Comment by HibernalGlow** [comment]
后面再反复打开闪卡也比较快了，启动需要时间？

**Comment by OpaqueGlass** [comment]
看起来像是卡在sql了，这个没法并发，插件需要先知道当前是什么文档然后再继续

> 也可以看看这个：这里的延迟也这么大就没救了
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/04b8b4ea-040c-4806-80b4-787be6f3acf3)

**Comment by HibernalGlow** [comment]
![1710233666752.png](https://img2.imgtp.com/2024/03/12/Qoapv7p2.png)
确实快了

**Comment by HibernalGlow** [comment]
没问题了又，怪怪的，要不先发一版beta看看其他人怎么样

**Comment by OpaqueGlass** [comment]
除非发集市，没几个人用的😂

愿意反馈的可能也不多。

> 旁边那个“自动获取标题”，都开了3个issue了，但不看回复。

**Comment by HibernalGlow** [comment]
那种还是少数吧，我 在用的话有问题也会反馈的

**Comment by OpaqueGlass** [comment]
那就过几天直接在集市更新吧

**Comment by OpaqueGlass** [comment]
准备发布到集市，issue我先关闭了哈。

**Comment by HibernalGlow** [comment]
好

**Comment by OpaqueGlass** [comment]
目前找到的原因是，数据量大的话会卡，插件有点过于依赖思源的数据库查询了（5000个文档的话 280ms，<1000个文档 70ms）；之后看一下怎么处理， 关联 #44 ；

**Comment by HibernalGlow** [comment]
我3k个，确实会慢
