### ISSUE TITLE
去年今日或同日文档

### ISSUE THREAD

**Issue by Foundation-Maker** [OpaqueGlass/syplugin-hierarchyNavigate#46]
<img width="768" alt="image" src="https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/46839690/b5674133-ff54-4c70-849a-0ab6f50eebf8">

想法是在dailynote下的每日文档中，导航中，显示去年今日创建的相同文档。
根据文件中的属性判断是哪一天。然后显示在层级导航中。 默认开启。可以设置关闭功能。
但是，非daiynote就不用显示同日创建的文档了。

**Comment by Foundation-Maker** [comment]
<img width="951" alt="image" src="https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/46839690/2b58a089-47d3-4e79-88f2-2e83944111d4">
最好是直接匹配 【mm-dd】

**Comment by OpaqueGlass** [comment]
可以有（但我属实是不用dailynote，下下个版本更新吧）

这里需要注意的，我暂时只想到通过sql定位其他文档；
但目前多于2个用户反馈层级导航在文档数量大于3000时显示卡顿，使用sql查询在移动端、低性能电脑或首次查询时可能较慢。

**Comment by OpaqueGlass** [comment]
请关注下一版本更新，如有缺陷，请反馈；如和预期不符，请在本issue反馈，谢谢。
