### ISSUE TITLE
移动端层级导航会消失

### ISSUE THREAD

**Issue by Jiangshuon** [OpaqueGlass/syplugin-hierarchyNavigate#49]
1、随便打开一篇文档
2、打开间隔重复，刷闪卡，刷十几秒
3、关闭间隔重复，发现该文档层级导航消失了
4、换一篇文档，再切换回来，发现又有了

**Comment by OpaqueGlass** [comment]
感谢反馈，但这个bug和另一个已解决的bug相关联，暂时没有好的解决方法，需要再等待一段时间；

为了避免一些情况下切换文档之后没有正确替换而出现多个导航区的问题（这个问题大概是由于插件冲突引起的，不能稳定复现），移动端每次显示新的导航区时会移除所有已有的导航区；

间隔重复时打开新的导航区，这将移除已有的所有导航区；退出间隔重复并没有打开新的文档，不会触发插件更新，因而会消失。

**Comment by OpaqueGlass** [comment]
请在下一版本中关闭此项：
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/67343d1d-e836-4216-afb4-e4220128608e)

issue将被关闭，感谢反馈。
