### ISSUE TITLE
Bug In the Mobile version, Navigation doesn't update when switching to another page

### ISSUE THREAD

**Issue by vbn112233v** [OpaqueGlass/syplugin-hierarchyNavigate#50]
There is a bug in mobile, When switching to another page the navigation will keep showing the previous page hierarchy and sub pages. Making it impossible to navigate further. 

This bug only happens in mobile version and the plug in is working as intended in desktop. 

It seems that this bug only happened recently and the plug in was working as intended in previous versions. 

---
Here I'm on page 1 and navigation shows page 1

![Screenshot_20240413_234519_SiYuan](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/166956913/021260ba-3562-433b-ab56-e2f5f10f9bbd)

Now if I try to switch to page 2 the navigation will stay showing page 1 making it impossible to navigate to page 2 Sub-pages. 

![Screenshot_20240413_234542_SiYuan](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/166956913/9077195f-de02-48af-8faa-d5ee19d115e0)

**Comment by OpaqueGlass** [comment]
Thank you for your feedback.

It seems that the navigation will keep showing the previous document's page. For example, when switching from page 2 to page 3, the navigation of page 2 will be displayed; when switching from page 3 to page 1, the navigation of page 3 will be displayed. Is that correct?

Besides, please let me know the version of SiYuan you are using. I believe this issue should have appeared after v3.0.5.

**Comment by vbn112233v** [comment]
> Thank you for your feedback.
> 
> It seems that the navigation will keep showing the previous document's page. For example, when switching from page 2 to page 3, the navigation of page 2 will be displayed; when switching from page 3 to page 1, the navigation of page 3 will be displayed. Is that correct?
> 
> Besides, please let me know the version of SiYuan you are using. I believe this issue should have appeared after v3.0.5.

Yes, it's correct. The navigation will always be showing the previous page. 

I'm using version v3.0.8.

**Comment by OpaqueGlass** [comment]
I think this bug is related to SiYuan's update in v3.0.6. (I have reported this issue to Siyuan)

Maybe you can downgrade to v3.0.5 or an older version, or use the following beta plugin package temporarily. 

[package.zip](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/files/14970273/package.zip)

**Comment by vbn112233v** [comment]
> I think this bug is related to SiYuan's update in v3.0.6. (I have reported this issue to Siyuan)
> 
> Maybe you can downgrade to v3.0.5 or an older version, or use the following beta plugin package temporarily.
> 
> [package.zip](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/files/14970273/package.zip)

I installed the beta package and now the bug is fixed and the plug in is working as intended. 

Thanks for your help 😊

**Comment by OpaqueGlass** [comment]
The issue should no longer occur after Siyuan v3.0.10, even if you are not using the beta version. 
This issue will be closed. If you have any further problems, please reply directly. Thank you.
