### ISSUE TITLE
往年今日要怎么触发？好像不成功

### ISSUE THREAD

**Issue by mozhux** [OpaqueGlass/syplugin-hierarchyNavigate#51]
同一个笔记本下，今天的日记没有显示去年的同月同日的链接
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/46953371/15801bb8-101f-462f-b23c-d16d78a4a10c)
这是今年的，有对应的自定义属性。
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/46953371/1d94fb20-b9db-4b00-aa63-6a3674f8d61f)
这是去年的，有对应的自定义属性。且在一个笔记本下，但不在一个父文档下。
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/46953371/f9742be4-17df-483c-951d-752cba3de718)

**Comment by OpaqueGlass** [comment]
大概是个bug，感谢反馈

**Comment by OpaqueGlass** [comment]
已更新，麻烦再试一下

**Comment by OpaqueGlass** [comment]
由于长时间未回复，此issue将被关闭，感谢反馈。
