### ISSUE TITLE
开启插件，调整文档块标题字号大小后，块标位置不能跟着对齐

### ISSUE THREAD

**Issue by LoneFireBlossom** [OpaqueGlass/syplugin-hierarchyNavigate#52]
开启下面的CSS：

```
.protyle-title__input {
font-size: 1.45em !important;
}
```

并开启本插件后，会发现文档块标题的块标图标没有跟着对齐：
<img width="706" alt="image" src="https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/50087596/ca3828bc-668e-4344-b078-c398c52a2d26">

未开启其它任何第三方内容

我不知道这个问题应该反馈到软件那边还是插件这边，还是说应该由用户自己来修改CSS呢？先来插件这里发一下，我想是不是本插件调整图标定位的方法一刀切导致的？见https://github.com/mustakshif/Asri/issues/45#issuecomment-2058106583

**Comment by OpaqueGlass** [comment]
> 我不知道这个问题应该反馈到软件那边还是插件这边，还是说应该由用户自己来修改CSS呢？

反馈到思源吗？emm难说，一旦开始自定义就和思源没啥关系了；

> 我想是不是本插件调整图标定位的方法一刀切导致的？

是的吧，开启之后插件会直接设置css为`25px`，也就是应用下面的：（思源默认是`50%`）

```css
.protyle-title__icon {top: 25px;}
```

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/00798c0f-d121-4a5c-9641-fb39de265501)

关了这个选项然后自己调整一下？先开着issue，过段时间我看看能不能自动调整，目前是觉得不能；

**Comment by OpaqueGlass** [comment]
1. 由于icon和title是两个相邻的兄弟元素，在我所知的范围内，css做不到只改title style的情况下，对应调整icon；
2. 插件一次性的写入文档图标的样式，在这个时候，如果没有打开文档，也就没有文档标题，插件将无法获取用户的样式更改，也无法对应地调整icon的位置；
3. 问题的根源是插件将导航区插入了`.protyle-title`元素内，使得该元素变长，原本的`50%`也变成加长后的50%；插件通过css将绝对的，也算是一刀切的，将图标位置调回原位；
4. 插件可以不再将导航区插入`.protyle-title`内，这需要插件自己来响应“自适应宽度”的变化，可以实现、但这会导致一些性能损失，我认为没必要；

**Comment by OpaqueGlass** [comment]
请使用最新的alpha测试版，并：
1、关闭 外观、CSS中的“调整文档图标位置”
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/6794dd46-aba1-4c37-9ee3-e28542aaa411)
2、打开 试验田 中的 “导航区不再插在文档标题所在的HTML元素”
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/9ba8c5eb-850d-4f0a-a5e0-4c9acc8d0fb8)
3、如果已经打开了文档，需要关闭、重新打开；
