### ISSUE TITLE
使用docker部署的，文档层级导航插件的设置无法点击

### ISSUE THREAD

**Issue by leeima** [OpaqueGlass/syplugin-hierarchyNavigate#54]
如题
v3.0.14
麻烦大佬复现一下

**Comment by OpaqueGlass** [comment]
是打不开插件的设置页吗？这个复现了，下个版本修复，感谢反馈

```
crypto.randomUUID is not a function
在非Localhost、https安全环境以外无法使用，且Chrome需>92版本
```

**Comment by leeima** [comment]
> 是打不开插件的设置页吗？这个复现了，下个版本修复，感谢反馈
> 
> ```
> crypto.randomUUID is not a function
> 在非Localhost、https安全环境以外无法使用，且Chrome需>92版本
> ```
> 

收到，这么晚了，感谢大佬

**Comment by OpaqueGlass** [comment]
已经在集市更新，麻烦确认一下有没有修好

**Comment by leeima** [comment]
> 已经在集市更新，麻烦确认一下有没有修好

刚去看了，已修复，谢谢

**Comment by OpaqueGlass** [comment]
ok，那我关闭issue了，谢谢反馈。
