### ISSUE TITLE
有时分屏页签下不显示

### ISSUE THREAD

**Issue by zhoutaosheng** [OpaqueGlass/syplugin-hierarchyNavigate#56]
注：1.0.5 没有问题

**Comment by OpaqueGlass** [comment]
麻烦录屏或截图演示，谢谢。

以下是未复现GIF说明：
![0605未复现](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/d039ccee-0299-4263-b47d-3c153ab6c50c)

**Comment by zhoutaosheng** [comment]
见下面这个视频，将左边的页面，分屏到右边后，目录显示完全不正确了

https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/5683995/30101225-afc5-4b5d-83ed-b8b6b4274ca6

**Comment by zhoutaosheng** [comment]
> 见下面这个视频，将左边的页面，分屏到右边后，目录显示完全不正确了
> 
>  ScreenRecorderProject52.mp4

且已经关闭所有其他插件，选用默认主题

**Comment by OpaqueGlass** [comment]
看起来是分屏并移动之后不显示？
抱歉，暂未复现，我这边思源版本v3.0.17，可以的话，麻烦上传一下层级导航的设置文件，在`工作空间\data\storage\petal\syplugin-hierarchyNavigate`文件夹下；另外，请尝试在不显示时点击对应文档的页签，看看是否显示；

以下是复现尝试GIF：
![0605未复现2](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/f6e16c9f-031e-4209-b831-79b16ea3f45d)

**Comment by zhoutaosheng** [comment]
> 看起来是分屏并移动之后不显示？ 抱歉，暂未复现，我这边思源版本v3.0.17，可以的话，麻烦上传一下层级导航的设置文件，在`工作空间\data\storage\petal\syplugin-hierarchyNavigate`文件夹下；另外，请尝试在不显示时点击对应文档的页签，看看是否显示；
> 
> 以下是复现尝试GIF： ![0605未复现2](https://private-user-images.githubusercontent.com/52985952/336916266-f6e16c9f-031e-4209-b831-79b16ea3f45d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzU3NjAsIm5iZiI6MTcxNzYzNTQ2MCwicGF0aCI6Ii81Mjk4NTk1Mi8zMzY5MTYyNjYtZjZlMTZjOWYtMDMxZS00MjA5LWI4MzEtNzliMTZlYTNmNDVkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAwNTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NDc2OTYxYmM5OGZlMzVjOTZlMzc0ODEzNjY0MzA1M2Y5ZTFhZjYyZDZiZGI5ZDU5YmQwOGRiY2ZmZmFhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qbqjm7iK05_U7U6TZv_U_DkG9PU6E5LMaN1zOgZHYws) [ ![0605未复现2](https://private-user-images.githubusercontent.com/52985952/336916266-f6e16c9f-031e-4209-b831-79b16ea3f45d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzU3NjAsIm5iZiI6MTcxNzYzNTQ2MCwicGF0aCI6Ii81Mjk4NTk1Mi8zMzY5MTYyNjYtZjZlMTZjOWYtMDMxZS00MjA5LWI4MzEtNzliMTZlYTNmNDVkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAwNTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NDc2OTYxYmM5OGZlMzVjOTZlMzc0ODEzNjY0MzA1M2Y5ZTFhZjYyZDZiZGI5ZDU5YmQwOGRiY2ZmZmFhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qbqjm7iK05_U7U6TZv_U_DkG9PU6E5LMaN1zOgZHYws) ](https://private-user-images.githubusercontent.com/52985952/336916266-f6e16c9f-031e-4209-b831-79b16ea3f45d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzU3NjAsIm5iZiI6MTcxNzYzNTQ2MCwicGF0aCI6Ii81Mjk4NTk1Mi8zMzY5MTYyNjYtZjZlMTZjOWYtMDMxZS00MjA5LWI4MzEtNzliMTZlYTNmNDVkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAwNTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NDc2OTYxYmM5OGZlMzVjOTZlMzc0ODEzNjY0MzA1M2Y5ZTFhZjYyZDZiZGI5ZDU5YmQwOGRiY2ZmZmFhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qbqjm7iK05_U7U6TZv_U_DkG9PU6E5LMaN1zOgZHYws) [ ](https://private-user-images.githubusercontent.com/52985952/336916266-f6e16c9f-031e-4209-b831-79b16ea3f45d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzU3NjAsIm5iZiI6MTcxNzYzNTQ2MCwicGF0aCI6Ii81Mjk4NTk1Mi8zMzY5MTYyNjYtZjZlMTZjOWYtMDMxZS00MjA5LWI4MzEtNzliMTZlYTNmNDVkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAwNTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NDc2OTYxYmM5OGZlMzVjOTZlMzc0ODEzNjY0MzA1M2Y5ZTFhZjYyZDZiZGI5ZDU5YmQwOGRiY2ZmZmFhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qbqjm7iK05_U7U6TZv_U_DkG9PU6E5LMaN1zOgZHYws)

问题原因是与 思源版本有关，思源版本为 3.0.16 会有问题

但这边还必须使用 3.0.16，因为3.0.17 有bug，导致频繁地报运行错误
![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/5683995/316e9f54-7f5c-47b4-96ed-237cf1af32fe)

**Comment by OpaqueGlass** [comment]
我这里降级到v3.0.16也不能重现，先保留issue。分屏出问题一般是在刚刚启动思源，并且开启保留页签的情况下，不具有焦点的页签会这样。理论上点击文档的标签页（页签）是能够显示的；
状态异常的问题可以考虑带着思源日志（设置-关于-系统日志-导出）去社区发帖看看。

--- 

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/0cbedd45-fe66-46dc-8cf9-dd597409a5ee)
关闭这个（插件设置-试验田-导航区不再插在文档标题所在的HTML元素）试试，v1.0.5~v1.0.6主要是这个设置项默认开启了，我计划默认开启并且移除这个设置。如果问题仍然存在的话可以排除是插件升级的影响。

---
有时，思源给到的事件对应一个fn_none的页签，在这个情况下，无法插入；~~解决的话……允许多线程+等待（？）~~ 似乎是给出了一个错误的protyle，而且现在又无法复现了。

**Comment by OpaqueGlass** [comment]
如果你那边方便的话：(但也请理解，可能配合之后也无法解决问题）

在新版本插件设置-关于中，启用“显示详细日志并加入测试计划”

在问题复现前，`ctrl+shift+I`打开开发者工具，切换到console或控制台，filter或过滤输入层级导航，然后进行复现，请观察

1. 是否有 message提示“当前文档不可见”（思源提示，右上角）；
2. 是否有  “由于正在运行，部分刷新被停止” 的提示；

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/de8ec870-9789-4f01-9c8f-910f848d095d)

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/7a03926a-c303-44cf-a993-8e0aaa4bd567)

**Comment by zhoutaosheng** [comment]
好的，我继续留意观察下这个问题
