### ISSUE TITLE
开启【导航区不再插在文档标题所在的HTML元素】，文档关闭「自适应宽度」，文档宽度改变，导航区和文档错位

### ISSUE THREAD

**Issue by Achuan-2** [OpaqueGlass/syplugin-hierarchyNavigate#65]
![Clip_2024-08-06_16-17-17](https://github.com/user-attachments/assets/ea347b2b-c918-4fc7-9a25-cff27552a867)

文档关闭「自适应宽度」，文档宽度改变（比如把侧栏关闭），导航区和文档错位
![Clip_2024-08-06_15-38-12](https://github.com/user-attachments/assets/490118ca-e8da-44c8-9539-a9376172690b)

**Comment by OpaqueGlass** [comment]
暂时未能复现，请重启思源或`ctrl+shift+i` + `Ctrl+r`，如果问题仍然存在，请提供思源版本号、主题和代码片段信息，如果不能100%复现，请大致描述出现问题的情况（如文档开启数量），谢谢；

未能复现GIF说明：
![未复现说明#65(2)](https://github.com/user-attachments/assets/0dd04df0-c00a-46d2-bd28-8b4fad09f566)

**Comment by Achuan-2** [comment]
说错了，是关闭文档「自适应宽度」，有问题
使用的是新开的工作空间，思源笔记是最新版，之前的版本也一直有这个问题
![思源文档导航bug反馈](https://github.com/user-attachments/assets/9c972032-eb6c-4dd2-abaf-a5c2554df36b)

**Comment by OpaqueGlass** [comment]
哦哦，复现了，感谢反馈；

> 忘记当时怎么想的了，以为不开启自适应宽度、宽度就不会变化，所以在自适应宽度关闭后，插件没有监听宽度变化。

**Comment by OpaqueGlass** [comment]
修复版本已作为测试版（只在github）发布，我没有完整测试。

> 由于这个版本（下一发布版本）调整了鼠标悬停时文档名显示方式，对于另一issue中的代码片段（ #64 ），可能需要修改  `getAttribute('title')`为 `getAttribute('aria-label')`。

**Comment by Achuan-2** [comment]
@OpaqueGlass 
好的，谢谢
