### ISSUE TITLE
面包屑点了没反应

### ISSUE THREAD

**Issue by fengweiyuan** [OpaqueGlass/syplugin-hierarchyNavigate#66]
我的思源笔记是3.1.3版本， MAC M3芯片 14.5操作系统版本

<img width="828" alt="image" src="https://github.com/user-attachments/assets/97d3ee67-3ba2-467e-a72b-152838780cda">

这个问题大概是2024年7月末-8月冒出来的，之前点面包屑，能顺利返回到父目录。

**Comment by OpaqueGlass** [comment]
![未复现说明#66](https://github.com/user-attachments/assets/5d4f0f71-b262-4f1f-8381-3cb9588655bc)

未能复现，请查看上面GIF操作是否有所不同；

如果可以，请到插件设置-关于-打开“显示详细日志并加入测试计划”，`Ctrl+Shift+I`打开开发者工具，重新操作复现不能点击的情况，然后截图`Console`（或`控制台`）部分有关层级导航的日志；

另外，也可能是和其他插件或代码片段有所冲突，这种情况日志应该看不出什么。

**Comment by fengweiyuan** [comment]
现在问题再次发生了。打开开发者工具后，点击后，没有相关日志输入。可以远程展示给看，我微信是aaa777357

**Comment by OpaqueGlass** [comment]
哦哦，我的微信名是Sola，已经发送好友申请了

**Comment by OpaqueGlass** [comment]
问题可能与 #75 有关，请等待下个版本更新，谢谢。
