### ISSUE TITLE
编辑器宽度插件兼容问题：插件宽度与标题宽度不一致

### ISSUE THREAD

**Issue by TCOTC** [OpaqueGlass/syplugin-hierarchyNavigate#67]
![image](https://github.com/user-attachments/assets/c819a5e5-6775-49f9-a800-314fb8521ff8)

之前还好好的，更新之后跟[编辑器宽度](https://github.com/frostime/siyuan-center-width)插件不兼容了

![image](https://github.com/user-attachments/assets/4edd1fb1-cda2-4bfd-93aa-7355c3574e9b)

**Comment by TCOTC** [comment]
现在突然又好了，不知道是什么原因

**Comment by OpaqueGlass** [comment]
不确定是否和 “升级后上一版本的没有完全移除”相关， #68 中处理；

**Comment by TCOTC** [comment]
怪怪的，时好时坏

![image](https://github.com/user-attachments/assets/601f75f1-75dd-40dd-8d7b-f27cf33c3bf8)

![image](https://github.com/user-attachments/assets/ebb723c3-50e5-492e-9ff1-ce3c797c0b63)

**Comment by OpaqueGlass** [comment]
发一下插件设置`data\storage\petal\syplugin-hierarchyNavigate\settings_main.json`，以及是否打开了 自适应宽度

**Comment by TCOTC** [comment]
[settings_main.json](https://github.com/user-attachments/files/16726080/settings_main.json)

没有打开自适应宽度

**Comment by OpaqueGlass** [comment]
感谢反馈，才看到用了其他插件；

这个是因为思源关闭自适应宽度之后，宽度仍然会发生变化（ #65  https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/issues/65#issuecomment-2270706211 ），为了适配才如此，之前是不响应变化的，暂时先回退上一版吧。

**Comment by TCOTC** [comment]
刚刚发现，编辑器宽度一变就会导致问题

- 分屏后取消分屏
- 调整窗口大小
- 侧栏(取消)钉住

**Comment by OpaqueGlass** [comment]
关闭[编辑器宽度](https://github.com/frostime/siyuan-center-width)插件就问题吧？

**Comment by TCOTC** [comment]
关闭[编辑器宽度](https://github.com/frostime/siyuan-center-width)插件就没这个问题

**Comment by OpaqueGlass** [comment]
如果可以，麻烦参与测试，谢谢

https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases/tag/v1.3.1-alpha1

**Comment by TCOTC** [comment]
感觉 OK 了
