### ISSUE TITLE
“文档上级为笔记本时，父文档区域显示同级文档” -- 失效

### ISSUE THREAD

**Issue by Luyi365** [OpaqueGlass/syplugin-hierarchyNavigate#76]
如题，已关闭“同级文档”区域，打开“父文档”区域，文档处于最外层，“同级文档”不显示。

**Comment by OpaqueGlass** [comment]
感谢反馈，问题已确认，下个版本修复。

**Comment by OpaqueGlass** [comment]
没有其他严重问题的话，下个版本至少一周后发布；🙏

如果需要测试或使用修复后的版本，请到这里下载 https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases/tag/v1.4.2-beta1
