### ISSUE TITLE
最新的日记，上一篇和下一篇都是前一天的日记

### ISSUE THREAD

**Issue by Achuan-2** [OpaqueGlass/syplugin-hierarchyNavigate#78]
![PixPin_2024-11-04_00-57-51](https://github.com/user-attachments/assets/b28db91e-8661-4a6e-8507-3f3fa0f08f9a)

而且下一篇显示图标，上一篇错误显示图标

**Comment by OpaqueGlass** [comment]
感谢反馈，问题已确认，下个版本改进。

问题背景：1（插件在文档为日记，且文档树获取不到上一篇或下一篇时，按照时间升序获取上一篇或下一篇）
2（补充上一篇时使用的api没有给到图标，之前认为单独请求图标有些花时间）

（有修改）
- [ ] 1. 后续修改为：（快捷键、内容区逻辑一致）
  - [x] 默认：以文档树顺序为主；如果是文件夹中第一篇或最后一篇日记，则按照文档升降序补充缺失的相邻日记；文件名、自然排序、创建时间排序以外的排序方式，不补充；
  - [x] 选项强制：如果是日记，按照日记属性时间先后（升序）确定上一篇下一篇，不跟随文档树排序；

- [ ] 2. 确认请求图标后的耗时；
  - [x] 时间较长则修改为选项，不开启则仍然保持现状；
  - [ ] 时间正常则开启、不可更改；


如果有其他改进建议，欢迎提出。

**Comment by OpaqueGlass** [comment]
如果可以，请参与测试，谢谢 https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/releases/tag/v1.4.2-beta2

**Comment by Achuan-2** [comment]
![PixPin_2024-11-06_17-47-19](https://github.com/user-attachments/assets/ed2b6f5f-e167-4fac-865c-534558c8b679)
![PixPin_2024-11-06_17-47-30](https://github.com/user-attachments/assets/5b5dc2a8-ba34-48f3-8207-a5989bb9eb28)
暂时没什么问题，辛苦啦
