### ISSUE TITLE
父子兄显示文档数量

### ISSUE THREAD

**Issue by HopeLHP** [OpaqueGlass/syplugin-hierarchyNavigate#8]
希望可以在父子兄后面加上文档数量显示，例如子(10086)：
这样可以判断父子兄文档数量，可以让用户大致了解文档规模。

**Comment by OpaqueGlass** [comment]
感谢提议，这大概会作为一个设置项提供。
另外问一下关于这个有什么建议：我认为只有一个文档或没有文档时没必要显示个数，但这会和下面的子文档部分无法对齐；另外，个数不同时也会有这个问题；

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/59eb6dac-9557-42c5-9dc2-f409e0640903)

> PS 能用之后我先发给你个压缩包吧，我解决新建文档显示错误的问题之后才会发布到集市；
> 鼠标停在那里将显示个数；

**Comment by HopeLHP** [comment]
我也认为对齐是必要的。我想了几种方案，可以参考：
## 第一种
对齐数字，例如
>父（1）、子（7）
父（00）、子（07）

但是可能子文档的数字会很大，可以考虑上下父子两行位数的最大值作为统一显示的位数，例如父兄级是11个，子级是112个，则显示父兄（011），子（112）。
另外，似乎父文档一直是只有一个，是否在0或1时不显示可以再考虑。
## 第二种
文档名称换行后显示，即父子兄这些名称单行显示，文档名称另起一行。
这样可以父子兄名称行加上更多的元素，例如统计个数、字数，或者显示笔记本名称。
>父：【01】【父文档字数合计】【笔记本名称】等等
父文档名称
子：【12】【子文档字数合计】【笔记本名称】等等
子文档名称

目前是直接接在“子：”后面的，文档多了换行之后，也错位了，其实也挺突兀的。
<img width="1472" alt="image" src="https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/70339118/e0f606e5-3bba-4e09-b472-a550f36af5b9">

## 第三种
应该算第二种的变种，就是只在首行单列一行显示各种元素，例如：
>父（01） 子（12） 【子文档字数合计】【笔记本名称】
父：文档名称
子：文档名称

## 第四种
不直接显示数字，只光标悬浮显示，就像你的截图一样。



> ![image](https://user-images.githubusercontent.com/52985952/251456347-59eb6dac-9557-42c5-9dc2-f409e0640903.png)

**Comment by OpaqueGlass** [comment]
好的，感谢提出方案；

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/85fd01ec-5fa0-428c-9d78-b91643564687)
目前选择的是在开头加入一行信息，信息包括：
- 创建/更新时间；
- 子文档数量；
- 子文档字数合计；\* 子文档大于128个后，将不再统计，避免响应缓慢；

悬停显示文档个数保留，但父文档部分不显示；

> 目前是直接接在“子：”后面的，文档多了换行之后，也错位了，其实也挺突兀的。

我感觉只要换行了都挺错位的，目前凑合用的方法是：

- 隐藏“父：”“子：”提示词。
- 链接强制等宽。

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/6d3cc188-9ac8-4694-8ea8-9647ca96cc9c)

![image](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/assets/52985952/23a2ef24-5509-41c8-8a90-44e84d5170aa)

**Comment by OpaqueGlass** [comment]
v0.2.4已经发版，等待集市更新。如果还有问题，可以继续回帖，或新开issue，谢谢。
